/*
 * This file is generated by jOOQ.
 */
package com.crm.goods.db;


import com.crm.goods.db.tables.Goods;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrmGoods extends SchemaImpl {

    private static final long serialVersionUID = 535393108;

    /**
     * The reference instance of <code>crm-goods</code>
     */
    public static final CrmGoods CRM_GOODS = new CrmGoods();

    /**
     * The table <code>crm-goods.goods</code>.
     */
    public final Goods GOODS = Goods.GOODS;

    /**
     * No further instances allowed
     */
    private CrmGoods() {
        super("crm-goods", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Goods.GOODS);
    }
}
