/*
 * This file is generated by jOOQ.
 */
package com.crm.goods.db;


import com.crm.goods.db.tables.Goods;


/**
 * Convenience access to all tables in crm-goods
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crm-goods.goods</code>.
     */
    public static final Goods GOODS = Goods.GOODS;
}
