/*
 * This file is generated by jOOQ.
 */
package com.crm.member.db;


import com.crm.member.db.tables.Member;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrmMember extends SchemaImpl {

    private static final long serialVersionUID = 211152682;

    /**
     * The reference instance of <code>crm-member</code>
     */
    public static final CrmMember CRM_MEMBER = new CrmMember();

    /**
     * The table <code>crm-member.member</code>.
     */
    public final Member MEMBER = Member.MEMBER;

    /**
     * No further instances allowed
     */
    private CrmMember() {
        super("crm-member", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Member.MEMBER);
    }
}
