/*
 * This file is generated by jOOQ.
 */
package com.crm.member.db;


import com.crm.member.db.tables.Member;


/**
 * Convenience access to all tables in crm-member
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crm-member.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;
}
