/*
 * This file is generated by jOOQ.
 */
package com.crm.member.db;


import com.crm.member.db.tables.Member;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in testdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>testdb.member</code>.
     */
    public static final Member MEMBER = Member.MEMBER;
}
