/*
 * This file is generated by jOOQ.
 */
package com.crm.goods.db.tables.records;


import com.crm.goods.db.tables.Goods;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsRecord extends UpdatableRecordImpl<GoodsRecord> implements Record9<Integer, String, String, String, BigDecimal, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 365095644;

    /**
     * Setter for <code>crm-goods.goods.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>crm-goods.goods.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>crm-goods.goods.goods_no</code>. 商品编码
     */
    public void setGoodsNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>crm-goods.goods.goods_no</code>. 商品编码
     */
    public String getGoodsNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>crm-goods.goods.name</code>. 商品名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>crm-goods.goods.name</code>. 商品名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>crm-goods.goods.description</code>. 商品描述
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>crm-goods.goods.description</code>. 商品描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>crm-goods.goods.amount</code>. 商品金额
     */
    public void setAmount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>crm-goods.goods.amount</code>. 商品金额
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>crm-goods.goods.stock</code>. 库存
     */
    public void setStock(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>crm-goods.goods.stock</code>. 库存
     */
    public Integer getStock() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>crm-goods.goods.imgurl</code>. 商品图片地址
     */
    public void setImgurl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>crm-goods.goods.imgurl</code>. 商品图片地址
     */
    public String getImgurl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>crm-goods.goods.created</code>. 创建时间
     */
    public void setCreated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>crm-goods.goods.created</code>. 创建时间
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>crm-goods.goods.modified</code>. 修改时间
     */
    public void setModified(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>crm-goods.goods.modified</code>. 修改时间
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, BigDecimal, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, BigDecimal, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Goods.GOODS.ID;
    }

    @Override
    public Field<String> field2() {
        return Goods.GOODS.GOODS_NO;
    }

    @Override
    public Field<String> field3() {
        return Goods.GOODS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Goods.GOODS.DESCRIPTION;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Goods.GOODS.AMOUNT;
    }

    @Override
    public Field<Integer> field6() {
        return Goods.GOODS.STOCK;
    }

    @Override
    public Field<String> field7() {
        return Goods.GOODS.IMGURL;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Goods.GOODS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Goods.GOODS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGoodsNo();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public BigDecimal component5() {
        return getAmount();
    }

    @Override
    public Integer component6() {
        return getStock();
    }

    @Override
    public String component7() {
        return getImgurl();
    }

    @Override
    public LocalDateTime component8() {
        return getCreated();
    }

    @Override
    public LocalDateTime component9() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGoodsNo();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public BigDecimal value5() {
        return getAmount();
    }

    @Override
    public Integer value6() {
        return getStock();
    }

    @Override
    public String value7() {
        return getImgurl();
    }

    @Override
    public LocalDateTime value8() {
        return getCreated();
    }

    @Override
    public LocalDateTime value9() {
        return getModified();
    }

    @Override
    public GoodsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GoodsRecord value2(String value) {
        setGoodsNo(value);
        return this;
    }

    @Override
    public GoodsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GoodsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GoodsRecord value5(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public GoodsRecord value6(Integer value) {
        setStock(value);
        return this;
    }

    @Override
    public GoodsRecord value7(String value) {
        setImgurl(value);
        return this;
    }

    @Override
    public GoodsRecord value8(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GoodsRecord value9(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GoodsRecord values(Integer value1, String value2, String value3, String value4, BigDecimal value5, Integer value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsRecord
     */
    public GoodsRecord() {
        super(Goods.GOODS);
    }

    /**
     * Create a detached, initialised GoodsRecord
     */
    public GoodsRecord(Integer id, String goodsNo, String name, String description, BigDecimal amount, Integer stock, String imgurl, LocalDateTime created, LocalDateTime modified) {
        super(Goods.GOODS);

        set(0, id);
        set(1, goodsNo);
        set(2, name);
        set(3, description);
        set(4, amount);
        set(5, stock);
        set(6, imgurl);
        set(7, created);
        set(8, modified);
    }
}
