/*
 * This file is generated by jOOQ.
 */
package com.crm.goods.db.tables.records;


import com.crm.goods.db.tables.Goods;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GoodsRecord extends UpdatableRecordImpl<GoodsRecord> implements Record8<Integer, String, String, BigDecimal, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 264165250;

    /**
     * Setter for <code>crm-goods.goods.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>crm-goods.goods.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>crm-goods.goods.name</code>. 商品名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>crm-goods.goods.name</code>. 商品名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>crm-goods.goods.description</code>. 商品描述
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>crm-goods.goods.description</code>. 商品描述
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>crm-goods.goods.amount</code>. 商品金额
     */
    public void setAmount(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>crm-goods.goods.amount</code>. 商品金额
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>crm-goods.goods.stock</code>. 库存
     */
    public void setStock(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>crm-goods.goods.stock</code>. 库存
     */
    public Integer getStock() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>crm-goods.goods.imgurl</code>. 商品图片地址
     */
    public void setImgurl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>crm-goods.goods.imgurl</code>. 商品图片地址
     */
    public String getImgurl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>crm-goods.goods.created</code>. 创建时间
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>crm-goods.goods.created</code>. 创建时间
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>crm-goods.goods.modified</code>. 修改时间
     */
    public void setModified(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>crm-goods.goods.modified</code>. 修改时间
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, BigDecimal, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, BigDecimal, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Goods.GOODS.ID;
    }

    @Override
    public Field<String> field2() {
        return Goods.GOODS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Goods.GOODS.DESCRIPTION;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Goods.GOODS.AMOUNT;
    }

    @Override
    public Field<Integer> field5() {
        return Goods.GOODS.STOCK;
    }

    @Override
    public Field<String> field6() {
        return Goods.GOODS.IMGURL;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Goods.GOODS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Goods.GOODS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public BigDecimal component4() {
        return getAmount();
    }

    @Override
    public Integer component5() {
        return getStock();
    }

    @Override
    public String component6() {
        return getImgurl();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public LocalDateTime component8() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public BigDecimal value4() {
        return getAmount();
    }

    @Override
    public Integer value5() {
        return getStock();
    }

    @Override
    public String value6() {
        return getImgurl();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public LocalDateTime value8() {
        return getModified();
    }

    @Override
    public GoodsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GoodsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GoodsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public GoodsRecord value4(BigDecimal value) {
        setAmount(value);
        return this;
    }

    @Override
    public GoodsRecord value5(Integer value) {
        setStock(value);
        return this;
    }

    @Override
    public GoodsRecord value6(String value) {
        setImgurl(value);
        return this;
    }

    @Override
    public GoodsRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public GoodsRecord value8(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public GoodsRecord values(Integer value1, String value2, String value3, BigDecimal value4, Integer value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GoodsRecord
     */
    public GoodsRecord() {
        super(Goods.GOODS);
    }

    /**
     * Create a detached, initialised GoodsRecord
     */
    public GoodsRecord(Integer id, String name, String description, BigDecimal amount, Integer stock, String imgurl, LocalDateTime created, LocalDateTime modified) {
        super(Goods.GOODS);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, amount);
        set(4, stock);
        set(5, imgurl);
        set(6, created);
        set(7, modified);
    }
}
