/*
 * This file is generated by jOOQ.
 */
package com.crm.member.db.tables.records;


import com.crm.member.db.tables.Member;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> implements Record7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1758246023;

    /**
     * Setter for <code>crm-member.member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>crm-member.member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>crm-member.member.member_code</code>. 会员编号
     */
    public void setMemberCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>crm-member.member.member_code</code>. 会员编号
     */
    public String getMemberCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>crm-member.member.name</code>. 会员名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>crm-member.member.name</code>. 会员名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>crm-member.member.mobile</code>. 手机号
     */
    public void setMobile(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>crm-member.member.mobile</code>. 手机号
     */
    public String getMobile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>crm-member.member.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>crm-member.member.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(4);
    }

    /**
     * Setter for <code>crm-member.member.created</code>. 创建时间
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>crm-member.member.created</code>. 创建时间
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>crm-member.member.modified</code>. 修改时间
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>crm-member.member.modified</code>. 修改时间
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Member.MEMBER.ID;
    }

    @Override
    public Field<String> field2() {
        return Member.MEMBER.MEMBER_CODE;
    }

    @Override
    public Field<String> field3() {
        return Member.MEMBER.NAME;
    }

    @Override
    public Field<String> field4() {
        return Member.MEMBER.MOBILE;
    }

    @Override
    public Field<String> field5() {
        return Member.MEMBER.REMARK;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Member.MEMBER.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Member.MEMBER.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMemberCode();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getMobile();
    }

    @Override
    public String component5() {
        return getRemark();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMemberCode();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getMobile();
    }

    @Override
    public String value5() {
        return getRemark();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public MemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MemberRecord value2(String value) {
        setMemberCode(value);
        return this;
    }

    @Override
    public MemberRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MemberRecord value4(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public MemberRecord value5(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public MemberRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public MemberRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public MemberRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Integer id, String memberCode, String name, String mobile, String remark, LocalDateTime created, LocalDateTime modified) {
        super(Member.MEMBER);

        set(0, id);
        set(1, memberCode);
        set(2, name);
        set(3, mobile);
        set(4, remark);
        set(5, created);
        set(6, modified);
    }
}
